# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forme.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QStringListModel

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(698, 541)
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(70, 410, 171, 41))
        self.pushButton1.setObjectName("pushButton1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 120, 171, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 190, 221, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 270, 141, 20))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(80, 350, 104, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 350, 141, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(240, 110, 46, 26))
        self.spinBox.setObjectName("spinBox")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(430, 350, 131, 26))
        self.toolButton.setObjectName("toolButton")
        self.lineEdit1 = QtWidgets.QLineEdit(Form)
        self.lineEdit1.setGeometry(QtCore.QRect(240, 30, 113, 28))
        self.lineEdit1.setObjectName("lineEdit1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 131, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(240, 177, 291, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 260, 291, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.dialog = QFileDialog()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton1.setText(_translate("Form", "Send"))
        self.label.setText(_translate("Form", "Le nombre de champts :"))
        self.label_2.setText(_translate("Form", "Les indexs( separer par des virgules)  :"))
        self.label_3.setText(_translate("Form", "Les liste des entetes :"))
        self.radioButton.setText(_translate("Form", "Un fichier"))
        self.radioButton_2.setText(_translate("Form", "Plusieurs fichiers"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label_4.setText(_translate("Form", "Cractere separateur :"))

    def getfile(self):
        print('you are clicked this method')
        fname = self.dialog.getOpenFileName(self, 'Open file', 
         'c:\\',"Image files (*.jpg *.gif)")
        return fname

    def getfiles(self):
        self.dialog.setFileMode(QFileDialog.AnyFile)
        self.dialog.setFilter("Text files (*.txt)")
        filenames = QStringListModel()
        return filenames

    def select_file(self):
        if self.radioButton.isChecked():
             self.toolButton.clicked.connect(self.getfile())
        elif self.radioButton_2.isChecked():
             self.toolButton.clicked.connect(self.getfiles())
        else:
            raise "error file not found"

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
